apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-2
spec:
  selector:
    matchLabels:
      app: grpc-client-2
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-client-2
    spec:
      containers:
      - name: grpc-client-2
        image: swapnildahiphale/grpc-client
        ports:
        - containerPort: 10000
          name: grpc
          protocol: TCP
        env:
          - name: USER
            value: 'user2'

